#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#


#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: 1.0.0


#
# list of participating organizations in this network
#

organizations:
  VlinkOrgMSP:
    mspid: VlinkOrgMSP
    cryptoPath:  peerOrganizations/0/users/{username}@0/msp
    peers:
      - user0.0
      - user1.0
      - copyright0.0
      - copyright1.0
    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - ca0.0
  # the profile will contain public information about organizations other than the one it belongs to.
  # These are necessary information to make transaction lifecycles work, including MSP IDs and
  # peers with a public URL to send transaction proposals. The file will not contain private
  # information reserved for members of the organization, such as admin key and certificate,
  # fabric-ca registrar enroll ID and secret, etc.
#
# The client section used by GO SDK.
#
client:
  organization: VlinkOrgMSP
  logging:
    level: info
  eventService:
    type: eventhub
  # Root of the MSP directories with keys and certs.
  cryptoconfig:
    path: /Users/joker/go/src/vlink.com/v2/vlink-blockchain-network/containers/test/crypto-config

  # Some SDKs support pluggable KV stores, the properties under "credentialStore"
  # are implementation specific
  credentialStore:
    # [Optional]. Used by user store. Not needed if all credentials are embedded in configuration
    # and enrollments are performed elswhere.
    path: "/tmp/hyperledger/state-store"

    # [Optional]. Specific to the CryptoSuite implementation used by GO SDK. Software-based implementations
    # requiring a key store. PKCS#11 based implementations does not.
    cryptoStore:
      # Specific to the underlying KeyValueStore that backs the crypto key store.
      path: '/tmp/hyperledger/store'

    # BCCSP config for the client. Used by GO SDK.
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256
  tlsCerts:
    systemCertPool: false
    client:
      key:
        path:
      cert:
        path:
channels:
  userchannel:
    peers:
      user0.0:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      

  copyrightchannel:
    peers:
      copyright0.0:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true




orderers:
  orderer0.0:
    url: orderer0.0:6050
    grpcOptions:
      ssl-target-name-override: orderer0.0
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /Users/joker/go/src/vlink.com/v2/vlink-blockchain-network/containers/test/crypto-config/ordererOrganizations/0/tlsca/tlsca.0-cert.pem

  orderer1.0:
    url: orderer1.0:6051
    grpcOptions:
      ssl-target-name-override: orderer1.0
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /Users/joker/go/src/vlink.com/v2/vlink-blockchain-network/containers/test/crypto-config/ordererOrganizations/0/tlsca/tlsca.0-cert.pem
  orderer2.0:
    url: orderer2.0:6052
    grpcOptions:
      ssl-target-name-override: orderer2.0
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /Users/joker/go/src/vlink.com/v2/vlink-blockchain-network/containers/test/crypto-config/ordererOrganizations/0/tlsca/tlsca.0-cert.pem


  orderer3.0:
    url: orderer3.0:6053
    grpcOptions:
      ssl-target-name-override: ordere3.0
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /Users/joker/go/src/vlink.com/v2/vlink-blockchain-network/containers/test/crypto-config/ordererOrganizations/0/tlsca/tlsca.0-cert.pem

  orderer4.0:
    url: orderer4.0:6054
    grpcOptions:
      ssl-target-name-override: orderer4.0
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /Users/joker/go/src/vlink.com/v2/vlink-blockchain-network/containers/test/crypto-config/ordererOrganizations/0/tlsca/tlsca.0-cert.pem


peers:
  user0.0:
    url: user0.0:11051
    grpcOptions:
      ssl-target-name-override: user0.0
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /Users/joker/go/src/vlink.com/v2/vlink-blockchain-network/containers/test/crypto-config/peerOrganizations/0/tlsca/tlsca.0-cert.pem

  copyright0.0:
    url: copyright0.0:10051
    grpcOptions:
      ssl-target-name-override: copyright0.0
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /Users/joker/go/src/vlink.com/v2/vlink-blockchain-network/containers/test/crypto-config/peerOrganizations/0/tlsca/tlsca.0-cert.pem
certificateAuthorities:
  ca0.0:
    url: https://ca.0:7054
    tlsCACerts:
      path: /Users/joker/go/src/vlink.com/v2/vlink-blockchain-network/containers/test/crypto-config/peerOrganizations/0/peers/ca0.0/tls/ca.crt
      client:
        key:
          path: /Users/joker/go/src/vlink.com/v2/vlink-blockchain-network/containers/test/crypto-config/peerOrganizations/0/peers/ca0.0/tls/server.key
        cert:
          path: /Users/joker/go/src/vlink.com/v2/vlink-blockchain-network/containers/test/crypto-config/peerOrganizations/0/peers/ca0.0/tls/server.crt
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca0.0
