---
Organizations:
    - &OrdererOrg
        Name: OrdererMSP
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/bidsun.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
    - &BidsunMSP
        Name: BidsunMSP
        ID: BidsunMSP
        MSPDir: crypto-config/peerOrganizations/bidsun.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('BidsunMSP.admin', 'BidsunMSP.peer', 'BidsunMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('BidsunMSP.admin', 'BidsunMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('BidsunMSP.admin')"
        AnchorPeers:
            - Host: peer.bidsun.com
              Port: 11051

    - &GuangzhouMSP
        Name: GuangzhouMSP
        ID: GuangzhouMSP
        MSPDir: crypto-config/peerOrganizations/guangzhou.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('GuangzhouMSP.admin', 'GuangzhouMSP.peer', 'GuangzhouMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('GuangzhouMSP.admin', 'GuangzhouMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('GuangzhouMSP.admin')"
        AnchorPeers:
            - Host: peer.guangzhaou.com
              Port: 12051

Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: false
        V1_3: false
        V1_1: false

    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false

    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities
Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.bidsun.com:5050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    ebidsun-global:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *BidsunMSP
                - *GuangzhouMSP
            Capabilities:
                <<: *ApplicationCapabilities
    OrdererRaftGenesis:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                    - Host: orderer.bidsun.com
                      Port: 7050
                      ClientTLSCert: crypto-config/ordererOrganizations/bidsun.com/orderers/orderer.bidsun.com/tls/server.crt
                      ServerTLSCert: crypto-config/ordererOrganizations/bidsun.com/orderers/orderer.bidsun.com/tls/server.crt
#                    - Host: orderer1.bidsun.com
#                      Port: 5051
#                      ClientTLSCert: crypto-config/ordererOrganizations/bidsun.com/orderers/orderer1.bidsun.com/tls/server.crt
#                      ServerTLSCert: crypto-config/ordererOrganizations/bidsun.com/orderers/orderer1.bidsun.com/tls/server.crt
#                    - Host: orderer2.bidsun.com
#                      Port: 5052
#                      ClientTLSCert: crypto-config/ordererOrganizations/bidsun.com/orderers/orderer2.bidsun.com/tls/server.crt
#                      ServerTLSCert: crypto-config/ordererOrganizations/bidsun.com/orderers/orderer2.bidsun.com/tls/server.crt
#                    - Host: orderer3.bidsun.com
#                      Port: 5053
#                      ClientTLSCert: crypto-config/ordererOrganizations/bidsun.com/orderers/orderer3.bidsun.com/tls/server.crt
#                      ServerTLSCert: crypto-config/ordererOrganizations/bidsun.com/orderers/orderer3.bidsun.com/tls/server.crt
#                    - Host: orderer4.bidsun.com
#                      Port: 5054
#                      ClientTLSCert: crypto-config/ordererOrganizations/bidsun.com/orderers/orderer4.bidsun.com/tls/server.crt
#                      ServerTLSCert: crypto-config/ordererOrganizations/bidsun.com/orderers/orderer4.bidsun.com/tls/server.crt
            Addresses:
                - orderer.bidsun.com:5050
#                - orderer1.bidsun.com:5051
#                - orderer2.bidsun.com:5052
#                - orderer3.bidsun.com:5053
#                - orderer4.bidsun.com:5054
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - <<: *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *GuangzhouMSP
                    - *BidsunMSP

