goPath: /Users/joker/go
cryptVersion: 1
configPath: /Users/joker/go/src/examples/blockchain/manualca/cmd/blockchain-config-local.yaml
channels:
  - channelId: ebidsun-alpha
    needListOnBlockEvent: false
    channelConfigPath: /Users/joker/go/src/examples/blockchain/manualca/artifacts/demochannel.tx
    orders:
      - ordererId: orderer.ebidsun.com
        ordererAddress: orderer.ebidsun.com
        ordererPort: 7050
    organizations:
      - organizationId: BidsunMSP
        users:
          - userName: 'Admin'
            admin: true
        peer:
          endorserPeers:
            - address: peer0.bidsun.com
              port: 7051
              chainCodes:
                - chainCodeId: tt_example
                  chainCodePath: bidchain/chaincode/tt_example
                  needUpdate: false
                - chainCodeId: enterprise
                  chainCodePath: bidchain/chaincode/enterprise
                  needUpdate: false
                - chainCodeId: platform
                  chainCodePath: bidchain/chaincode/platform
                  needUpdate: false
                - chainCodeId: cryptomessage
                  chainCodePath: bidchain/chaincode/cryptomessage
                  needUpdate: false
                - chainCodeId: tender_project
                  chainCodePath: bidchain/chaincode/tender_project
                  needUpdate: false
                - chainCodeId: tender_project
                  chainCodePath: bidchain/chaincode/tender_project
                  needUpdate: false
        ca:
          caName: 'org.ca.demo.com'
