version: 1.0.0
organizations:
  Org0MSP:
    mspid: Org0MSP
    cryptoPath:  peerOrganizations/bidsun.com/users/{username}@bidsun.com/msp
    peers:
      - peer1.bidsun.com
    certificateAuthorities:
      - org.ca.bidsun.com
client:
  organization: Org0MSP
  logging:
    level: info
  eventService:
    type: eventhub
  # Root of the MSP directories with keys and certs.
  cryptoconfig:
    path: /Users/joker/go/src/examples/blockchain/manualca/crypto-config

  credentialStore:
    path: "/tmp/hyperledger/state-store"
    cryptoStore:
      path: '/tmp/hyperledger/store'
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256
  tlsCerts:
    systemCertPool: false
    client:
      key:
        path:
      cert:
        path:
channels:
  demochannel:
    peers:
      peer1.bidsun.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
orderers:
  orderer0.bidsun.com:
    url: orderer0.bidsun.com:5050
    grpcOptions:
      ssl-target-name-override: orderer0.bidsun.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /Users/joker/go/src/examples/blockchain/manualca/crypto-config/ordererOrganizations/bidsun.com/tlsca/ca.crt

peers:
  peer1.bidsun.com:
    url: peer1.bidsun.com:11051
    grpcOptions:
      ssl-target-name-override: peer1.bidsun.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: /Users/joker/go/src/examples/blockchain/manualca/crypto-config/peerOrganizations/bidsun.com/tlsca/ca-cert.pem

certificateAuthorities:
  org.ca.bidsun.com:
    url: https://org.ca.bidsun.com:4054
    tlsCACerts:
      path: /Users/joker/go/src/examples/blockchain/manualca/crypto-config/peerOrganizations/bidsun.com/msp/ca.crt
      client:
        key:
          path: /Users/joker/go/src/examples/blockchain/manualca/crypto-config/peerOrganizations/bidsun.com/msp/server.key
        cert:
          path: /Users/joker/go/src/examples/blockchain/manualca/crypto-config/peerOrganizations/bidsun.com/msp/server.crt
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName:
      org.ca.bidsun.com